version: 2

multi-ecosystem-groups:
  github-actions:
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "chore"
      include: "scope"
  api:
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "chore"
      include: "scope"
  frontend:
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "chore"
      include: "scope"
  github-service:
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "chore"
      include: "scope"
  k8s-service:
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "chore"
      include: "scope"

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    multi-ecosystem-group: "github-actions"
    patterns:
      - "*"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      github-actions-major-versions:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "npm"
    directory: "/api"
    multi-ecosystem-group: "api"
    patterns:
      - "*"
    labels:
      - "dependencies"
      - "api"
    groups:
      api-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      api-major-versions:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "docker"
    directory: "/api"
    multi-ecosystem-group: "api"
    patterns:
      - "*"
    labels:
      - "dependencies"
      - "docker"
      - "api"
    groups:
      api-docker-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      api-docker-major-versions:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "npm"
    directory: "/frontend"
    multi-ecosystem-group: "frontend"
    patterns:
      - "*"
    labels:
      - "dependencies"
      - "frontend"
    groups:
      frontend-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      frontend-major-versions:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "docker"
    directory: "/frontend"
    multi-ecosystem-group: "frontend"
    patterns:
      - "*"
    labels:
      - "dependencies"
      - "docker"
      - "frontend"
    groups:
      frontend-docker-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      frontend-docker-major-versions:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "npm"
    directory: "/github-service"
    multi-ecosystem-group: "github-service"
    patterns:
      - "*"
    labels:
      - "dependencies"
      - "github-service"
    groups:
      github-service-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      github-service-major-versions:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "docker"
    directory: "/github-service"
    multi-ecosystem-group: "github-service"
    patterns:
      - "*"
    labels:
      - "dependencies"
      - "docker"
      - "github-service"
    groups:
      github-service-docker-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      github-service-docker-major-versions:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "gomod"
    directory: "/k8s-service"
    multi-ecosystem-group: "k8s-service"
    patterns:
      - "*"
    labels:
      - "dependencies"
      - "k8s-service"
    groups:
      k8s-service-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      k8s-service-major-versions:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "docker"
    directory: "/k8s-service"
    multi-ecosystem-group: "k8s-service"
    patterns:
      - "*"
    labels:
      - "dependencies"
      - "docker"
      - "k8s-service"
    groups:
      k8s-service-docker-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      k8s-service-docker-major-versions:
        patterns:
          - "*"
        update-types:
          - "major"
