FROM oven/bun:1-alpine

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY . .

EXPOSE 3000

ENV NODE_ENV=development
ENV HOST=0.0.0.0
ENV NODE_OPTIONS="--max-old-space-size=1536"

CMD ["bun", "run", "dev", "--", "--host", "0.0.0.0"]
