apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "k8s-service.fullname" . }}-allow-same-namespace
  labels:
    {{- include "k8s-service.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "k8s-service.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
