apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-service.fullname" . }}-secrets
  labels:
    {{- include "k8s-service.labels" . | nindent 4 }}
type: Opaque
data:
  RABBITMQ: {{ .Values.secrets.RABBITMQ | b64enc | quote }}
  RABBITMQ_HTTP: {{ .Values.secrets.RABBITMQ_HTTP | b64enc | quote }}
  S3_ACCESS_KEY_ID: {{ .Values.secrets.S3_ACCESS_KEY_ID | b64enc | quote }}
  S3_SECRET_ACCESS_KEY: {{ .Values.secrets.S3_SECRET_ACCESS_KEY | b64enc | quote }}
