apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-service.fullname" . }}
  labels:
    {{- include "k8s-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "k8s-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default 9000 }}
      protocol: TCP
