name: Production
description: Production environment for the main branch
url: https://coregame.de
protection_rules:
  required_reviewers: 2
  prevent_self_review: true
  dismiss_stale_reviews: true
deployment_branch_policy:
  protected_branches: true
  custom_branch_policies: false
variables:
  ENVIRONMENT_NAME: production
  NAMESPACE: production
  DOMAIN: coregame.de
  VALUES_FILE: values-prod.yaml 