apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: core-local
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seaweedfs-data
  namespace: core-local
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
