apiVersion: v1
kind: ConfigMap
metadata:
  name: seaweedfs-s3-config
  namespace: core-local
data:
  s3.json: |
    {
      "identities": [
        {
          "name": "core",
          "credentials": [
            {
              "accessKey": "core",
              "secretKey": "coresecret"
            }
          ],
          "actions": [
            "Admin",
            "Read",
            "Write"
          ]
        }
      ]
    }
