FROM oven/bun:1.3.11-alpine
RUN apk add --no-cache git

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY . .

RUN git config --global user.name "corethegame" && \
    git config --global user.email "core@paulgrossmann.de"

EXPOSE 3000

CMD ["bun", "run", "start:dev"]
