autoscaling:
  enabled: false

replicaCount: 1

service:
  type: ClusterIP
  port: 3000

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: nginx
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

env:
  GITHUB_ID: xxx
  GITHUB_SECRET: xxx
  GITHUB_TOKEN: xxx
  GITHUB_RUSH_TOKEN: xxx
  NEXT_PUBLIC_GITHUB_ORG: 42-core-repos
  NEXT_PUBLIC_RUSH_ORG: 42-core-rush-repos

  NEXTAUTH_SECRET: xxx
  NEXTAUTH_URL: http://localhost:3000/

  DATABASE_URL: xxx