services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    networks:
      - development-network

  pocketbase:
    image: ghcr.io/paulicstudios/pocketbase:latest
    restart: unless-stopped
    volumes:
      - pocketbase-data:/home/pocketbase/pb_data
      - ../pocketbase/pb_migrations:/home/pocketbase/pb_migrations
    ports:
      - 8090:8090
    networks:
      - development-network

networks:
  development-network:

volumes:
  pocketbase-data: