services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    networks:
      - development-network

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - development-network

  rabbitmq:
    image: rabbitmq:4-management
    restart: unless-stopped
    ports:
      - "15672:15672"
    networks:
      - development-network

networks:
  development-network:

volumes:
  postgres-data:
