services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: host

  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - development-network

  rabbitmq:
    image: rabbitmq:4-management
    restart: unless-stopped
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - development-network

  prometheus:
    image: prom/prometheus:v3.5.0
    restart: unless-stopped
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - development-network

  tempo:
    image: grafana/tempo:2.8.1
    restart: unless-stopped
    command:
      - "-config.file=/etc/tempo/tempo.yml"
    ports:
      - "3200:3200"
      - "4318:4318"
    volumes:
      - ./tempo/tempo.yml:/etc/tempo/tempo.yml:ro
    networks:
      - development-network

  grafana:
    image: grafana/grafana:12.1.1
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
      - tempo
    networks:
      - development-network

networks:
  development-network:

volumes:
  postgres-data:
  grafana-data:
