/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WikiRouteImport } from './routes/wiki'
import { Route as RushRouteImport } from './routes/rush'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WikiSplatRouteImport } from './routes/wiki.$'
import { Route as EventsCreateRouteImport } from './routes/events/create'
import { Route as EventsIdRouteImport } from './routes/events/$id'
import { Route as EventsIdTeamsRouteImport } from './routes/events/$id/teams'
import { Route as EventsIdQueueMatchesRouteImport } from './routes/events/$id/queue-matches'
import { Route as EventsIdQueueRouteImport } from './routes/events/$id/queue'
import { Route as EventsIdMyTeamRouteImport } from './routes/events/$id/my-team'
import { Route as EventsIdGroupsRouteImport } from './routes/events/$id/groups'
import { Route as EventsIdDashboardRouteImport } from './routes/events/$id/dashboard'
import { Route as EventsIdBracketRouteImport } from './routes/events/$id/bracket'
import { Route as EventsIdTeamsTeamIdRouteImport } from './routes/events/$id/teams/$teamId'
import { Route as EventsIdMatchMatchIdRouteImport } from './routes/events/$id/match/$matchId'

const WikiRoute = WikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const RushRoute = RushRouteImport.update({
  id: '/rush',
  path: '/rush',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiSplatRoute = WikiSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => WikiRoute,
} as any)
const EventsCreateRoute = EventsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => EventsRoute,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EventsRoute,
} as any)
const EventsIdTeamsRoute = EventsIdTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => EventsIdRoute,
} as any)
const EventsIdQueueMatchesRoute = EventsIdQueueMatchesRouteImport.update({
  id: '/queue-matches',
  path: '/queue-matches',
  getParentRoute: () => EventsIdRoute,
} as any)
const EventsIdQueueRoute = EventsIdQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => EventsIdRoute,
} as any)
const EventsIdMyTeamRoute = EventsIdMyTeamRouteImport.update({
  id: '/my-team',
  path: '/my-team',
  getParentRoute: () => EventsIdRoute,
} as any)
const EventsIdGroupsRoute = EventsIdGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => EventsIdRoute,
} as any)
const EventsIdDashboardRoute = EventsIdDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => EventsIdRoute,
} as any)
const EventsIdBracketRoute = EventsIdBracketRouteImport.update({
  id: '/bracket',
  path: '/bracket',
  getParentRoute: () => EventsIdRoute,
} as any)
const EventsIdTeamsTeamIdRoute = EventsIdTeamsTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => EventsIdTeamsRoute,
} as any)
const EventsIdMatchMatchIdRoute = EventsIdMatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => EventsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/datenschutz': typeof DatenschutzRoute
  '/events': typeof EventsRouteWithChildren
  '/impressum': typeof ImpressumRoute
  '/profile': typeof ProfileRoute
  '/rush': typeof RushRoute
  '/wiki': typeof WikiRouteWithChildren
  '/events/$id': typeof EventsIdRouteWithChildren
  '/events/create': typeof EventsCreateRoute
  '/wiki/$': typeof WikiSplatRoute
  '/events/$id/bracket': typeof EventsIdBracketRoute
  '/events/$id/dashboard': typeof EventsIdDashboardRoute
  '/events/$id/groups': typeof EventsIdGroupsRoute
  '/events/$id/my-team': typeof EventsIdMyTeamRoute
  '/events/$id/queue': typeof EventsIdQueueRoute
  '/events/$id/queue-matches': typeof EventsIdQueueMatchesRoute
  '/events/$id/teams': typeof EventsIdTeamsRouteWithChildren
  '/events/$id/match/$matchId': typeof EventsIdMatchMatchIdRoute
  '/events/$id/teams/$teamId': typeof EventsIdTeamsTeamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/datenschutz': typeof DatenschutzRoute
  '/events': typeof EventsRouteWithChildren
  '/impressum': typeof ImpressumRoute
  '/profile': typeof ProfileRoute
  '/rush': typeof RushRoute
  '/wiki': typeof WikiRouteWithChildren
  '/events/$id': typeof EventsIdRouteWithChildren
  '/events/create': typeof EventsCreateRoute
  '/wiki/$': typeof WikiSplatRoute
  '/events/$id/bracket': typeof EventsIdBracketRoute
  '/events/$id/dashboard': typeof EventsIdDashboardRoute
  '/events/$id/groups': typeof EventsIdGroupsRoute
  '/events/$id/my-team': typeof EventsIdMyTeamRoute
  '/events/$id/queue': typeof EventsIdQueueRoute
  '/events/$id/queue-matches': typeof EventsIdQueueMatchesRoute
  '/events/$id/teams': typeof EventsIdTeamsRouteWithChildren
  '/events/$id/match/$matchId': typeof EventsIdMatchMatchIdRoute
  '/events/$id/teams/$teamId': typeof EventsIdTeamsTeamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/datenschutz': typeof DatenschutzRoute
  '/events': typeof EventsRouteWithChildren
  '/impressum': typeof ImpressumRoute
  '/profile': typeof ProfileRoute
  '/rush': typeof RushRoute
  '/wiki': typeof WikiRouteWithChildren
  '/events/$id': typeof EventsIdRouteWithChildren
  '/events/create': typeof EventsCreateRoute
  '/wiki/$': typeof WikiSplatRoute
  '/events/$id/bracket': typeof EventsIdBracketRoute
  '/events/$id/dashboard': typeof EventsIdDashboardRoute
  '/events/$id/groups': typeof EventsIdGroupsRoute
  '/events/$id/my-team': typeof EventsIdMyTeamRoute
  '/events/$id/queue': typeof EventsIdQueueRoute
  '/events/$id/queue-matches': typeof EventsIdQueueMatchesRoute
  '/events/$id/teams': typeof EventsIdTeamsRouteWithChildren
  '/events/$id/match/$matchId': typeof EventsIdMatchMatchIdRoute
  '/events/$id/teams/$teamId': typeof EventsIdTeamsTeamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/changelog'
    | '/datenschutz'
    | '/events'
    | '/impressum'
    | '/profile'
    | '/rush'
    | '/wiki'
    | '/events/$id'
    | '/events/create'
    | '/wiki/$'
    | '/events/$id/bracket'
    | '/events/$id/dashboard'
    | '/events/$id/groups'
    | '/events/$id/my-team'
    | '/events/$id/queue'
    | '/events/$id/queue-matches'
    | '/events/$id/teams'
    | '/events/$id/match/$matchId'
    | '/events/$id/teams/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/changelog'
    | '/datenschutz'
    | '/events'
    | '/impressum'
    | '/profile'
    | '/rush'
    | '/wiki'
    | '/events/$id'
    | '/events/create'
    | '/wiki/$'
    | '/events/$id/bracket'
    | '/events/$id/dashboard'
    | '/events/$id/groups'
    | '/events/$id/my-team'
    | '/events/$id/queue'
    | '/events/$id/queue-matches'
    | '/events/$id/teams'
    | '/events/$id/match/$matchId'
    | '/events/$id/teams/$teamId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/changelog'
    | '/datenschutz'
    | '/events'
    | '/impressum'
    | '/profile'
    | '/rush'
    | '/wiki'
    | '/events/$id'
    | '/events/create'
    | '/wiki/$'
    | '/events/$id/bracket'
    | '/events/$id/dashboard'
    | '/events/$id/groups'
    | '/events/$id/my-team'
    | '/events/$id/queue'
    | '/events/$id/queue-matches'
    | '/events/$id/teams'
    | '/events/$id/match/$matchId'
    | '/events/$id/teams/$teamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChangelogRoute: typeof ChangelogRoute
  DatenschutzRoute: typeof DatenschutzRoute
  EventsRoute: typeof EventsRouteWithChildren
  ImpressumRoute: typeof ImpressumRoute
  ProfileRoute: typeof ProfileRoute
  RushRoute: typeof RushRoute
  WikiRoute: typeof WikiRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wiki': {
      id: '/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rush': {
      id: '/rush'
      path: '/rush'
      fullPath: '/rush'
      preLoaderRoute: typeof RushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$': {
      id: '/wiki/$'
      path: '/$'
      fullPath: '/wiki/$'
      preLoaderRoute: typeof WikiSplatRouteImport
      parentRoute: typeof WikiRoute
    }
    '/events/create': {
      id: '/events/create'
      path: '/create'
      fullPath: '/events/create'
      preLoaderRoute: typeof EventsCreateRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/$id/teams': {
      id: '/events/$id/teams'
      path: '/teams'
      fullPath: '/events/$id/teams'
      preLoaderRoute: typeof EventsIdTeamsRouteImport
      parentRoute: typeof EventsIdRoute
    }
    '/events/$id/queue-matches': {
      id: '/events/$id/queue-matches'
      path: '/queue-matches'
      fullPath: '/events/$id/queue-matches'
      preLoaderRoute: typeof EventsIdQueueMatchesRouteImport
      parentRoute: typeof EventsIdRoute
    }
    '/events/$id/queue': {
      id: '/events/$id/queue'
      path: '/queue'
      fullPath: '/events/$id/queue'
      preLoaderRoute: typeof EventsIdQueueRouteImport
      parentRoute: typeof EventsIdRoute
    }
    '/events/$id/my-team': {
      id: '/events/$id/my-team'
      path: '/my-team'
      fullPath: '/events/$id/my-team'
      preLoaderRoute: typeof EventsIdMyTeamRouteImport
      parentRoute: typeof EventsIdRoute
    }
    '/events/$id/groups': {
      id: '/events/$id/groups'
      path: '/groups'
      fullPath: '/events/$id/groups'
      preLoaderRoute: typeof EventsIdGroupsRouteImport
      parentRoute: typeof EventsIdRoute
    }
    '/events/$id/dashboard': {
      id: '/events/$id/dashboard'
      path: '/dashboard'
      fullPath: '/events/$id/dashboard'
      preLoaderRoute: typeof EventsIdDashboardRouteImport
      parentRoute: typeof EventsIdRoute
    }
    '/events/$id/bracket': {
      id: '/events/$id/bracket'
      path: '/bracket'
      fullPath: '/events/$id/bracket'
      preLoaderRoute: typeof EventsIdBracketRouteImport
      parentRoute: typeof EventsIdRoute
    }
    '/events/$id/teams/$teamId': {
      id: '/events/$id/teams/$teamId'
      path: '/$teamId'
      fullPath: '/events/$id/teams/$teamId'
      preLoaderRoute: typeof EventsIdTeamsTeamIdRouteImport
      parentRoute: typeof EventsIdTeamsRoute
    }
    '/events/$id/match/$matchId': {
      id: '/events/$id/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/events/$id/match/$matchId'
      preLoaderRoute: typeof EventsIdMatchMatchIdRouteImport
      parentRoute: typeof EventsIdRoute
    }
  }
}

interface EventsIdTeamsRouteChildren {
  EventsIdTeamsTeamIdRoute: typeof EventsIdTeamsTeamIdRoute
}

const EventsIdTeamsRouteChildren: EventsIdTeamsRouteChildren = {
  EventsIdTeamsTeamIdRoute: EventsIdTeamsTeamIdRoute,
}

const EventsIdTeamsRouteWithChildren = EventsIdTeamsRoute._addFileChildren(
  EventsIdTeamsRouteChildren,
)

interface EventsIdRouteChildren {
  EventsIdBracketRoute: typeof EventsIdBracketRoute
  EventsIdDashboardRoute: typeof EventsIdDashboardRoute
  EventsIdGroupsRoute: typeof EventsIdGroupsRoute
  EventsIdMyTeamRoute: typeof EventsIdMyTeamRoute
  EventsIdQueueRoute: typeof EventsIdQueueRoute
  EventsIdQueueMatchesRoute: typeof EventsIdQueueMatchesRoute
  EventsIdTeamsRoute: typeof EventsIdTeamsRouteWithChildren
  EventsIdMatchMatchIdRoute: typeof EventsIdMatchMatchIdRoute
}

const EventsIdRouteChildren: EventsIdRouteChildren = {
  EventsIdBracketRoute: EventsIdBracketRoute,
  EventsIdDashboardRoute: EventsIdDashboardRoute,
  EventsIdGroupsRoute: EventsIdGroupsRoute,
  EventsIdMyTeamRoute: EventsIdMyTeamRoute,
  EventsIdQueueRoute: EventsIdQueueRoute,
  EventsIdQueueMatchesRoute: EventsIdQueueMatchesRoute,
  EventsIdTeamsRoute: EventsIdTeamsRouteWithChildren,
  EventsIdMatchMatchIdRoute: EventsIdMatchMatchIdRoute,
}

const EventsIdRouteWithChildren = EventsIdRoute._addFileChildren(
  EventsIdRouteChildren,
)

interface EventsRouteChildren {
  EventsIdRoute: typeof EventsIdRouteWithChildren
  EventsCreateRoute: typeof EventsCreateRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsIdRoute: EventsIdRouteWithChildren,
  EventsCreateRoute: EventsCreateRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface WikiRouteChildren {
  WikiSplatRoute: typeof WikiSplatRoute
}

const WikiRouteChildren: WikiRouteChildren = {
  WikiSplatRoute: WikiSplatRoute,
}

const WikiRouteWithChildren = WikiRoute._addFileChildren(WikiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChangelogRoute: ChangelogRoute,
  DatenschutzRoute: DatenschutzRoute,
  EventsRoute: EventsRouteWithChildren,
  ImpressumRoute: ImpressumRoute,
  ProfileRoute: ProfileRoute,
  RushRoute: RushRoute,
  WikiRoute: WikiRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
