# Development environment values
replicaCount: 1

autoscaling:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  NODE_ENV: production
  # NextAuth Configuration
  NEXTAUTH_URL: "https://dev.coregame.de"
  # GitHub OAuth Configuration
  CLIENT_ID_GITHUB: "dev-github-client-id"
  # 42 OAuth Configuration - public variable
  NEXT_PUBLIC_FORTY_TWO_CLIENT_ID: "dev-42-client-id"
  # Backend API Configuration
  BACKEND_URL: "https://dev.api.coregame.de"
  NEXT_PUBLIC_VISUALIZER_URL: "https://dev.visualizer.coregame.de"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: dev.coregame.de
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - dev.coregame.de
      secretName: dev-coregame-de-tls

nodeSelector: {}
tolerations: []
affinity: {}

# Secrets - these should be provided via GitHub secrets during deployment
secrets:
  NEXTAUTH_SECRET: ""
  CLIENT_SECRET_GITHUB: ""
  BACKEND_SECRET: ""
  # 42 OAuth Client Secret - sensitive data
  FORTY_TWO_CLIENT_SECRET: ""
  # Provide a dev encryption key (AES-GCM) via CI/CD secret injection
  NEXT_SERVER_ACTIONS_ENCRYPTION_KEY: ""
