allowBuilds:
  '@nestjs/core': set this to true or false
  '@scarf/scarf': set this to true or false
  '@swc/core': true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@swc/core'
  - unrs-resolver
