allowBuilds:
  '@scarf/scarf': false
  '@swc/core': false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - prettier@3.9.1
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@swc/core'
  - unrs-resolver
