name: Deploy API

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-api

jobs:
  deploy:
    runs-on: ubuntu-24.04
    environment: api-${{ inputs.environment }}

    permissions:
      contents: read
      packages: read
      deployments: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create deployment
        id: deployment
        uses: actions/github-script@v7
        with:
          script: |
            const deployment = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha,
              environment: 'api-${{ inputs.environment }}',
              description: 'Deploying API to ${{ inputs.environment }}',
              auto_merge: false,
              required_contexts: []
            });

            core.setOutput('deployment_id', deployment.data.id);
            return deployment.data.id;

      - name: Set deployment status to in progress
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: '${{ steps.deployment.outputs.deployment_id }}',
              state: 'in_progress',
              description: 'Deployment started'
            });

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: "v3.13.3"

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "v1.28.4"

      - name: Configure Kubernetes context
        run: |
          # Debug: Check if KUBECONFIG_DATA is set
          if [ -z "${{ secrets.KUBECONFIG_DATA }}" ]; then
            echo "ERROR: KUBECONFIG_DATA secret is empty or not set!"
            echo "Please ensure KUBECONFIG_DATA is configured in the GitHub environment: api-${{ inputs.environment }}"
            exit 1
          fi

          # Create .kube directory
          mkdir -p ~/.kube

          # Try to decode with better error handling
          if ! echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > ~/.kube/config 2>/tmp/base64_error; then
            echo "ERROR: Failed to decode base64 secret"
            echo "Base64 error output:"
            cat /tmp/base64_error
            echo "This usually means the secret is not properly base64 encoded"
            exit 1
          fi

          chmod 600 ~/.kube/config

          # Verify connection
          kubectl cluster-info
          kubectl get nodes

      - name: Configure deployment settings
        id: config
        run: |
          ENVIRONMENT="${{ inputs.environment }}"
          SHORT_SHA="${GITHUB_SHA::7}"
          IMAGE_TAG="sha-${SHORT_SHA}"
          IMAGE_REPO="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"

          # Sanitize branch name for Kubernetes resources
          BRANCH_NAME="${{ github.ref_name }}"
          SANITIZED_BRANCH=$(echo "${BRANCH_NAME}" | sed 's/[^a-zA-Z0-9._-]/-/g' | sed 's/--*/-/g' | sed 's/^-\|-$//g')

          # Set configuration based on environment
          case "${ENVIRONMENT}" in
            "prod")
              VALUES_FILE="values-prod.yaml"
              NAMESPACE="production"
              ENVIRONMENT_URL="https://api.coregame.de"
              ;;
            "dev")
              VALUES_FILE="values-dev.yaml"
              NAMESPACE="development"
              ENVIRONMENT_URL="https://dev.api.coregame.de"
              ;;
            *)
              echo "Unknown environment: ${ENVIRONMENT}"
              exit 1
              ;;
          esac

          echo "environment=${ENVIRONMENT}" >> $GITHUB_OUTPUT
          echo "branch=${BRANCH_NAME}" >> $GITHUB_OUTPUT
          echo "sanitized_branch=${SANITIZED_BRANCH}" >> $GITHUB_OUTPUT
          echo "values_file=${VALUES_FILE}" >> $GITHUB_OUTPUT
          echo "namespace=${NAMESPACE}" >> $GITHUB_OUTPUT
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "image_repo=${IMAGE_REPO}" >> $GITHUB_OUTPUT
          echo "release_name=api-${SANITIZED_BRANCH}" >> $GITHUB_OUTPUT
          echo "environment_url=${ENVIRONMENT_URL}" >> $GITHUB_OUTPUT

          echo "Deployment Configuration:"
          echo "- Environment: ${ENVIRONMENT}"
          echo "- Branch: ${BRANCH_NAME} (sanitized: ${SANITIZED_BRANCH})"
          echo "- Values file: ${VALUES_FILE}"
          echo "- Namespace: ${NAMESPACE}"
          echo "- Image tag: ${IMAGE_TAG}"
          echo "- Image repo: ${IMAGE_REPO}"
          echo "- Release name: api-${SANITIZED_BRANCH}"
          echo "- Environment URL: ${ENVIRONMENT_URL}"

      - name: Create image pull secret
        run: |
          kubectl create secret docker-registry ghcr-secret \
            --docker-server=ghcr.io \
            --docker-username=${{ github.actor }} \
            --docker-password=${{ secrets.GITHUB_TOKEN }} \
            --docker-email=${{ github.actor }}@users.noreply.github.com \
            --namespace=${{ steps.config.outputs.namespace }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy API with Helm
        run: |
          cd api/helm

          echo "Deploying API to ${{ steps.config.outputs.environment }} environment..."
          echo "Using values file: ${{ steps.config.outputs.values_file }}"
          echo "Image: ${{ steps.config.outputs.image_repo }}:${{ steps.config.outputs.image_tag }}"

          helm upgrade --install \
            ${{ steps.config.outputs.release_name }} \
            . \
            --namespace ${{ steps.config.outputs.namespace }} \
            --values ${{ steps.config.outputs.values_file }} \
            --set image.tag=${{ steps.config.outputs.image_tag }} \
            --set image.repository=${{ steps.config.outputs.image_repo }} \
            --set env.DB_HOST="${{ vars.DB_HOST }}" \
            --set env.DB_PORT="${{ vars.DB_PORT }}" \
            --set env.DB_USER="${{ vars.DB_USER }}" \
            --set env.DB_NAME="${{ vars.DB_NAME }}" \
            --set env.K8S_SERVICE_URL="${{ vars.K8S_SERVICE_URL }}" \
            --set env.DB_SCHEMA="${{ vars.DB_SCHEMA }}" \
            --set secrets.DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            --set secrets.DB_URL="${{ secrets.DB_URL }}" \
            --set secrets.API_SECRET_ENCRYPTION_KEY="${{ secrets.API_SECRET_ENCRYPTION_KEY }}" \
            --set secrets.FRONTEND_SECRET="${{ secrets.FRONTEND_SECRET }}" \
            --set secrets.RABBITMQ_URL="${{ secrets.RABBITMQ_URL }}" \
            --wait \
            --timeout=10m \
            --atomic \
            --history-max=5

      - name: Verify deployment
        run: |
          echo "Verifying API deployment..."

          DEPLOYMENT_NAME="${{ steps.config.outputs.release_name }}"
          NAMESPACE="${{ steps.config.outputs.namespace }}"

          # Check deployment status
          kubectl get deployment $DEPLOYMENT_NAME -n $NAMESPACE

          # Check pod status
          kubectl get pods -l app.kubernetes.io/name=api,app.kubernetes.io/instance=${{ steps.config.outputs.release_name }} -n $NAMESPACE

          # Check service status
          kubectl get svc $DEPLOYMENT_NAME -n $NAMESPACE

      - name: Set deployment status to success
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: '${{ steps.deployment.outputs.deployment_id }}',
              state: 'success',
              description: 'Deployment completed successfully',
              environment_url: '${{ steps.config.outputs.environment_url }}'
            });

      - name: Set deployment status to failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: '${{ steps.deployment.outputs.deployment_id }}',
              state: 'failure',
              description: 'Deployment failed'
            });

      - name: Update deployment status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "## ✅ API Deployment Successful" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Environment:** ${{ steps.config.outputs.environment }}" >> $GITHUB_STEP_SUMMARY
            echo "**Namespace:** ${{ steps.config.outputs.namespace }}" >> $GITHUB_STEP_SUMMARY
            echo "**Release:** ${{ steps.config.outputs.release_name }}" >> $GITHUB_STEP_SUMMARY
            echo "**Image:** ${{ steps.config.outputs.image_repo }}:${{ steps.config.outputs.image_tag }}" >> $GITHUB_STEP_SUMMARY
            echo "**URL:** ${{ steps.config.outputs.environment_url }}" >> $GITHUB_STEP_SUMMARY
          else
            echo "## ❌ API Deployment Failed" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Environment:** ${{ steps.config.outputs.environment }}" >> $GITHUB_STEP_SUMMARY
            echo "**Image:** ${{ steps.config.outputs.image_repo }}:${{ steps.config.outputs.image_tag }}" >> $GITHUB_STEP_SUMMARY
            echo "**Check the logs above for details**" >> $GITHUB_STEP_SUMMARY
          fi
