name: Debug Secrets Access

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to test'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - beta
          - prod

jobs:
  debug-secrets:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
    
    permissions:
      contents: read

    steps:
      - name: Debug Secret Access
        run: |
          echo "🔍 Debugging secret access for environment: ${{ inputs.environment }}"
          echo ""
          
          # Check if secrets exist (without revealing values)
          echo "📋 Secret availability check:"
          
          if [ -n "${{ secrets.KUBECONFIG_DATA }}" ]; then
            echo "✅ KUBECONFIG_DATA secret is accessible"
            echo "   Length: ${#KUBECONFIG_DATA} characters"
            echo "   First 20 chars: ${KUBECONFIG_DATA:0:20}..."
          else
            echo "❌ KUBECONFIG_DATA secret is NOT accessible"
          fi
          
          echo ""
          echo "🔧 Environment context:"
          echo "- Environment: ${{ inputs.environment }}"
          echo "- Runner: ${{ runner.os }}"
          echo "- Repository: ${{ github.repository }}"
          echo "- Actor: ${{ github.actor }}"
          
          echo ""
          echo "📝 Troubleshooting steps:"
          echo "1. Verify secret exists in Settings → Environments → ${{ inputs.environment }} → Environment secrets"
          echo "2. Verify secret exists in Settings → Secrets and variables → Actions → Repository secrets"
          echo "3. Check secret name is exactly 'KUBECONFIG_DATA' (case-sensitive)"
          echo "4. Verify you have admin access to the repository"
          echo "5. Try recreating the secret"
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}

  debug-no-environment:
    runs-on: ubuntu-latest
    # No environment specified - should only access repository secrets
    
    permissions:
      contents: read

    steps:
      - name: Debug Repository Secret Access
        run: |
          echo "🔍 Testing repository secret access (no environment context)"
          echo ""
          
          if [ -n "${{ secrets.KUBECONFIG_DATA }}" ]; then
            echo "✅ KUBECONFIG_DATA repository secret is accessible"
            echo "   Length: ${#KUBECONFIG_DATA} characters"
            echo "   First 20 chars: ${KUBECONFIG_DATA:0:20}..."
          else
            echo "❌ KUBECONFIG_DATA repository secret is NOT accessible"
          fi
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }} 