name: Build and Push Docker Image

on:
  push:
    branches: [main, dev, 60-helm-chart]
  pull_request:
    branches: [main, dev, 60-helm-chart]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: X64
            platform: linux/amd64
            arch: amd64
          - runner: ARM64
            platform: linux/arm64
            arch: arm64
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr,prefix=pr-
            type=sha,prefix={{branch}}-,format=short

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v5
        timeout-minutes: 30
        with:
          context: .
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }},push-by-digest=true,name-canonical=true,push=true
          cache-from: type=gha,scope=${{ matrix.arch }}
          cache-to: type=gha,mode=max,scope=${{ matrix.arch }}

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.arch }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch name
        id: branch
        run: |
          # Extract branch name from GITHUB_REF and sanitize for Docker tags
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          # Replace invalid characters for Docker tags (only allow a-z, A-Z, 0-9, -, _, .)
          SANITIZED_BRANCH=$(echo "${BRANCH_NAME}" | sed 's/[^a-zA-Z0-9._-]/-/g' | sed 's/--*/-/g' | sed 's/^-\|-$//g')
          echo "name=${SANITIZED_BRANCH}" >> $GITHUB_OUTPUT
          echo "original=${BRANCH_NAME}" >> $GITHUB_OUTPUT
          echo "Original branch name: ${BRANCH_NAME}"
          echo "Sanitized branch name: ${SANITIZED_BRANCH}"

      - name: Generate tags
        id: tags
        run: |
          BRANCH_NAME="${{ steps.branch.outputs.name }}"
          ORIGINAL_BRANCH="${{ steps.branch.outputs.original }}"
          REGISTRY="${{ env.REGISTRY }}"
          IMAGE_NAME="${{ env.IMAGE_NAME }}"
          
          # Base tags
          TAGS="${REGISTRY}/${IMAGE_NAME}:${BRANCH_NAME}"
          
          # Add latest tag for main branch
          if [ "${ORIGINAL_BRANCH}" = "main" ]; then
            TAGS="${TAGS},${REGISTRY}/${IMAGE_NAME}:latest"
          fi
          
          # Add short SHA tag
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          TAGS="${TAGS},${REGISTRY}/${IMAGE_NAME}:${BRANCH_NAME}-${SHORT_SHA}"
          
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
          echo "Generated tags: ${TAGS}"

      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          # Create multi-arch manifest for each tag
          TAGS="${{ steps.tags.outputs.tags }}"
          IFS=',' read -ra TAG_ARRAY <<< "$TAGS"
          
          for TAG in "${TAG_ARRAY[@]}"; do
            echo "Creating manifest for tag: $TAG"
            docker buildx imagetools create -t "$TAG" \
              $(printf '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@sha256:%s ' *)
          done

      - name: Inspect image
        run: |
          BRANCH_NAME="${{ steps.branch.outputs.name }}"
          echo "Inspecting multi-arch image for branch: ${BRANCH_NAME}"
          docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${BRANCH_NAME}

      - name: Output image details
        run: |
          echo "## Multi-arch Image Created" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Branch:** ${{ steps.branch.outputs.original }}" >> $GITHUB_STEP_SUMMARY
          echo "**Tags created:**" >> $GITHUB_STEP_SUMMARY
          
          TAGS="${{ steps.tags.outputs.tags }}"
          IFS=',' read -ra TAG_ARRAY <<< "$TAGS"
          for TAG in "${TAG_ARRAY[@]}"; do
            echo "- \`${TAG}\`" >> $GITHUB_STEP_SUMMARY
          done
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Supported architectures:** linux/amd64, linux/arm64" >> $GITHUB_STEP_SUMMARY

  # Summary job to show what was built
  summary:
    runs-on: ubuntu-latest
    needs: [build, merge]
    if: always()
    steps:
      - name: Build Summary
        run: |
          echo "## Docker Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ github.event_name }}" = "push" ]; then
            ORIGINAL_BRANCH=${GITHUB_REF#refs/heads/}
            SANITIZED_BRANCH=$(echo "${ORIGINAL_BRANCH}" | sed 's/[^a-zA-Z0-9._-]/-/g' | sed 's/--*/-/g' | sed 's/^-\|-$//g')
            
            echo "✅ **Multi-arch image built and pushed for branch:** \`${ORIGINAL_BRANCH}\`" >> $GITHUB_STEP_SUMMARY
            
            if [ "${ORIGINAL_BRANCH}" != "${SANITIZED_BRANCH}" ]; then
              echo "   *(Docker tag uses sanitized name: \`${SANITIZED_BRANCH}\`)*" >> $GITHUB_STEP_SUMMARY
            fi
            
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Available tags:**" >> $GITHUB_STEP_SUMMARY
            echo "- \`${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${SANITIZED_BRANCH}\`" >> $GITHUB_STEP_SUMMARY
            
            if [ "${ORIGINAL_BRANCH}" = "main" ]; then
              echo "- \`${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest\`" >> $GITHUB_STEP_SUMMARY
            fi
            
            SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
            echo "- \`${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${SANITIZED_BRANCH}-${SHORT_SHA}\`" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Architectures:** linux/amd64, linux/arm64" >> $GITHUB_STEP_SUMMARY
          else
            echo "✅ **Multi-arch build completed for PR** (images not pushed)" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Architectures tested:** linux/amd64, linux/arm64" >> $GITHUB_STEP_SUMMARY
          fi 