name: Manual Deploy Frontend

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
      image_tag:
        description: 'Docker image tag to deploy'
        required: true
        default: 'latest'
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-frontend

jobs:
  deploy:
    uses: ./.github/workflows/frontend-deploy-reusable.yml
    with:
      environment: ${{ github.event.inputs.environment }}
      image_tag: ${{ github.event.inputs.image_tag }}
      image_repository: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} 