name: Build k8s-service

on:
  push:
    branches: [main, dev]
    paths:
      - "k8s-service/**"
      - ".github/workflows/k8s-service-build.yml"
  pull_request:
    branches: [main, dev]
    paths:
      - "k8s-service/**"
      - ".github/workflows/k8s-service-build.yml"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod
      image_tag:
        description: "Docker image tag to deploy"
        required: true
        default: "latest"
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-k8s-service

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        platform: [linux/amd64]
    permissions:
      contents: read
      packages: write
    outputs:
      short_sha: ${{ steps.short-sha.outputs.short_sha }}
      branch_tag: ${{ steps.compute-tag.outputs.branch_tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract short SHA
        id: short-sha
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Compute branch-shortsha tag
        id: compute-tag
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          SANITIZED_BRANCH=$(echo "${BRANCH_NAME}" | sed 's/[^a-zA-Z0-9._-]/-/g' | sed 's/--*/-/g' | sed 's/^-\|-$//g')
          TAG="${SANITIZED_BRANCH}-${{ steps.short-sha.outputs.short_sha }}"
          echo "branch_tag=${TAG}" >> $GITHUB_OUTPUT
          echo "Computed tag: ${TAG}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./k8s-service
          file: ./k8s-service/Dockerfile
          platforms: ${{ matrix.platform }}
          push: ${{ github.event_name == 'push' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.compute-tag.outputs.branch_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Output image details
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "## ✅ k8s-service Image Built and Pushed" >> $GITHUB_STEP_SUMMARY
          else
            echo "## 🔨 k8s-service Image Built (Not Pushed)" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Image:** ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}" >> $GITHUB_STEP_SUMMARY
          echo "**Tag:** ${{ steps.compute-tag.outputs.branch_tag }}" >> $GITHUB_STEP_SUMMARY
          echo "**Short SHA:** ${{ steps.short-sha.outputs.short_sha }}" >> $GITHUB_STEP_SUMMARY
          echo "**Event:** ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          echo "**Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY

  deploy:
    needs: build
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/k8s-service-deploy.yml
    with:
      environment: ${{ github.event_name == 'workflow_dispatch' && inputs.environment || (github.ref_name == 'main' && 'prod' || 'dev') }}
      image_tag: ${{ github.event_name == 'workflow_dispatch' && inputs.image_tag || needs.build.outputs.branch_tag }}
    secrets: inherit
