name: Simple Secret Test

on:
  workflow_dispatch:

jobs:
  test-repo-secret:
    runs-on: ubuntu-latest
    
    steps:
      - name: Test Repository Secret
        run: |
          echo "🔍 Testing KUBECONFIG_DATA repository secret access"
          echo ""
          
          if [ -z "${{ secrets.KUBECONFIG_DATA }}" ]; then
            echo "❌ KUBECONFIG_DATA repository secret is NOT accessible"
            echo ""
            echo "Please check:"
            echo "1. Go to Settings → Secrets and variables → Actions"
            echo "2. Verify 'KUBECONFIG_DATA' secret exists"
            echo "3. Check the secret name is exactly 'KUBECONFIG_DATA'"
            echo "4. Verify you have admin access to this repository"
          else
            echo "✅ KUBECONFIG_DATA repository secret IS accessible"
            echo "Secret length: ${#SECRET_VALUE} characters"
            echo "First 20 characters: ${SECRET_VALUE:0:20}..."
            
            # Test if it's valid base64
            if echo "${SECRET_VALUE}" | base64 -d > /dev/null 2>&1; then
              echo "✅ Secret appears to be valid base64"
            else
              echo "❌ Secret does not appear to be valid base64"
            fi
          fi
        env:
          SECRET_VALUE: ${{ secrets.KUBECONFIG_DATA }} 